{{- range $chain := $.Values.chains }}
{{- if $chain.persistence }}
{{- if $chain.persistence.enabled }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  {{ include "provider.fullname" $ }}-{{ $chain.name | lower }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "provider.labels" $ | nindent 4 }}
    app.lavanet.io/chain: {{ $chain.id | lower }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  {{- range $chain.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ $chain.persistence.size | quote }}
{{- end }}
{{- end }}
{{- end }}
