{{- range $chain := $.Values.chains }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "provider.fullname" $ }}-{{ $chain.name | lower }}
  labels:
    {{- include "provider.labels" $ | nindent 4 }}
    app.lavanet.io/chain: {{ $chain.name | lower }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  {{- if $.Values.metrics.enabled }}
    - port: {{ $.Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  {{- end }}
  selector:
    {{- include "provider.selectorLabels" $ | nindent 4 }}
    app.lavanet.io/chain: {{ $chain.name | lower }}
{{- end }}
