global:
  # -- Default domain used by all components
  ## Used for ingresses, certificates, etc.
  domain: my-provider.local

# -- The number of provider pods to run.
replicaCount: 1

image:
  # -- Repository to use for the provider
  repository: ghcr.io/lavanet/lava/lavap
  # -- Image pull policy for the provider
  pullPolicy: IfNotPresent
  # -- Tag to use for the provider
  # @default -- `""` (defaults to Chart.appVersion)
  tag: ""

# -- Secrets with credentials to pull images from a private registry
imagePullSecrets: []
# -- Provide a name in place of release name
nameOverride: ""
# -- String to fully override `"provider.fullname"`
fullnameOverride: ""

## -- Update strategy for StatefulSets
statefulSetUpdate:
  updateStrategy: RollingUpdate

## -- Update strategy for Deployments
deploymentUpdate:
  type: RollingUpdate
  maxUnavailable: 0
  maxSurge: 100%

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Annotations for the all deployed pods
podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  # -- Provider service type
  type: ClusterIP
  # -- Provider service port
  port: 2200

ingressGrpc:
  # -- Enable an ingress resource for the provider
  enabled: false
  # -- Defines which ingress controller will implement the resource
  className: "nginx"
  # -- Additional ingress annotations
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- Enable TLS configuration for the domain defined at `global.domain`
  ## TLS certificate will be retrieved from a TLS secret with name: `provider-grpc-tls`
  tls: true
  # -- The path to Provider
  path: /
  # -- Ingress path type. One of `Exact`, `Prefix` or `ImplementationSpecific`
  pathType: Prefix
  # -- Custom Ingress TLS secret
  tlsSecretName:

# TLS certificate configuration via cert-manager
certificate:
  # -- Deploy a Certificate resource (requires cert-manager)
  enabled: false
  # -- Certificate primary domain (commonName)
  # @default -- `""` (defaults to global.domain)
  domain: ""
  # -- Certificate Subject Alternate Names (SANs)
  additionalHosts: []
  # -- The requested 'duration' (i.e. lifetime) of the certificate.
  # @default -- `""` (defaults to 2160h = 90d if not specified)
  ## Ref: <https://cert-manager.io/docs/usage/certificate/#renewal>
  duration: ""
  # -- How long before the expiry a certificate should be renewed.
  # @default -- `""` (defaults to 360h = 15d if not specified)
  ## Ref: <https://cert-manager.io/docs/usage/certificate/#renewal>
  renewBefore: ""
  # Certificate issuer
  ## Ref: <https://cert-manager.io/docs/concepts/issuer>
  issuer:
    # -- Certificate issuer group. Set if using an external issuer. Eg. `cert-manager.io`
    group: ""
    # -- Certificate issuer kind. Either `Issuer` or `ClusterIssuer`
    kind: "ClusterIssuer"
    # -- Certificate issuer name. Eg. `letsencrypt`
    name: "selfsigned"
  # Private key of the certificate
  privateKey:
    # -- Rotation policy of private key when certificate is re-issued. Either: `Never` or `Always`
    rotationPolicy: Never
    # -- The private key cryptography standards (PKCS) encoding for private key. Either: `PCKS1` or `PKCS8`
    encoding: PKCS1
    # -- Algorithm used to generate certificate private key. One of: `RSA`, `Ed25519` or `ECDSA`
    algorithm: RSA
    # -- Key bit size of the private key. If algorithm is set to `Ed25519`, size is ignored.
    size: 2048
  # -- Annotations to be applied to the Server Certificate
  annotations: {}
  # -- Usages for the certificate
  ### Ref: <https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.KeyUsage>
  usages: []
  # -- Annotations that allow the certificate to be composed from data residing in existing Kubernetes Resources
  secretTemplateAnnotations: {}

## Probes for provider
readinessProbe:
  # -- Schema of the [probe], can be HTTP or HTTPS
  scheme: HTTPS
  # -- Minimum consecutive failures for the [probe] to be considered failed after having succeeded
  failureThreshold: 3
  # -- Number of seconds after the container has started before [probe] is initiated
  initialDelaySeconds: 10
  # -- How often (in seconds) to perform the [probe]
  periodSeconds: 10
  # -- Minimum consecutive successes for the [probe] to be considered successful after having failed
  successThreshold: 1
  # -- Number of seconds after which the [probe] times out
  timeoutSeconds: 1

livenessProbe:
  # -- Schema of the [probe], can be HTTP or HTTPS
  scheme: HTTPS
  # -- Minimum consecutive failures for the [probe] to be considered failed after having succeeded
  failureThreshold: 3
  # -- Number of seconds after the container has started before [probe] is initiated
  initialDelaySeconds: 10
  # -- How often (in seconds) to perform the [probe]
  periodSeconds: 10
  # -- Minimum consecutive successes for the [probe] to be considered successful after having failed
  successThreshold: 1
  # -- Number of seconds after which the [probe] times out
  timeoutSeconds: 1

# -- Resource limits and requests for the provider pods
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- [Node selector]
nodeSelector: {}

# -- [Tolerations] for use with node taints
tolerations: []

# -- Assign custom [affinity] rules to the deployment
affinity: {}

metrics:
  # -- Should enable prometheus metrics
  enabled: true
  # --  Metrics service port
  port: 3200
  serviceMonitor:
    # -- Enable a prometheus ServiceMonitor
    enabled: false
    # -- Prometheus ServiceMonitor interval
    interval: 30s
    # -- Prometheus [RelabelConfigs] to apply to samples before scraping
    relabelings: []
    # -- Prometheus [MetricRelabelConfigs] to apply to samples before ingestion
    metricRelabelings: []
    # -- Prometheus ServiceMonitor selector
    selector: {}
      # prometheus: kube-prometheus

    # -- Prometheus ServiceMonitor scheme
    scheme: ""
    # -- Prometheus ServiceMonitor tlsConfig
    tlsConfig: {}
    # -- Prometheus ServiceMonitor namespace
    namespace: "" # "monitoring"
    # -- Prometheus ServiceMonitor labels
    additionalLabels: {}
    # -- Prometheus ServiceMonitor annotations
    annotations: {}

log:
  # -- Provider log level
  level: info
  # -- Provider log format, can be json or text
  format: json

cache:
  # -- Enable provider cache supports
  enabled: true
  # -- Provider cache address
  address: provider-cache:20100

# -- Wallet name
wallet: "test"

# -- Information about the private key to use for the node
key:
  # -- The secret name containing the private key
  secretName: "wallet"
  # -- The key in the secret to use
  secretKey: "key"
  # -- The secret that contains the password for the private key
  passwordSecretName: "wallet"
  # -- The key in the secret that contains the password for the private key
  passwordSecretKey: "password"

# -- Provider keyring backend
keyringBackend: "test"
# -- Lava node to connect to
node: https://testnet2-rpc.lavapro.xyz:443
# -- Lava chain id
chainId: "lava-testnet-2"
# -- Provider geo-location can be one of the [geolocations](https://docs.lavanet.xyz/provider-setup#geolocations)
geolocation: "2"

# -- Lavap provider additional CLI arguments
additionalArgs: []
  # - --fees
  # - 10ulava
  # - --note
  # - "A personal note"

# @ignored
chains:
  # - id: lav1
  #   name: my-lav1
  #   resources:
  #     requests:
  #       cpu: 100m
  #       memory: 128Mi
  #     limits:
  #       cpu: 100m
  #       memory: 128Mi
  #   persistence:
  #     enabled: true
  #     accessModes:
  #       - "ReadWriteOnce"
  #     size: "100Mi"
  #   interfaces:
  #     - interface: rest
  #       disableTLS: true
  #       nodes:
  #         - endpoint: rest.example.com
  #           # addons:
  #           #   - full
  #         - endpoint: rest.archive.example.com
  #           addons:
  #             - archive
  #           skipVerifications: pruning
  #     - interface: tendermintrpc
  #       nodes:
  #         - endpoint: tendermintrpc.example.com
  #           addons:
  #             - full
  #         - endpoint: tendermintrpc.archive.example.com
  #           addons:
  #             - archive
  #           skipVerifications: pruning
  #     - interface: grpc
  #       nodes:
  #         - endpoint: grpc.example.com
  #           addons:
  #             - full
  #         - endpoint: grpc.archive.example.com
  #           addons:
  #             - archive
  #           skipVerifications: pruning
