{{- range $itemKey, $itemValue := $.Values.chains }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $itemKey | lower }}-{{ include "consumer.fullname" $ }}
  labels:
    {{- include "consumer.labels" $ | nindent 4 }}
data:
  config.yml: |
    {{- $interfaces := dict }}
    {{- range .interfaces }}
    {{- $_ := set $interfaces .interface . }}
    {{- end }}

    endpoints:
    {{- range $interfaceEntry := $interfaces }}
      - chain-id: {{ $itemKey | upper }}
        api-interface: {{ $interfaceEntry.interface }}
        network-address: 0.0.0.0:{{ $interfaceEntry.port }}
    {{- end }}

    static-providers:
    {{- range $interfaceEntry := $itemValue.interfaces }}
    {{- if $interfaceEntry.staticProviders }}
      - chain-id: {{ $itemKey | upper }}
        api-interface: {{ $interfaceEntry.interface }}
        node-urls:
        {{- range $staticProvider := $interfaceEntry.staticProviders }}
          - url: {{ $staticProvider.url }}
            {{- if $staticProvider.addons }}
            addons:
              {{- range $addon := $staticProvider.addons }}
              - {{ $addon | lower }}
              {{- end }}
            {{- end }}
        {{- end }}
    {{- end }}
    {{- end }}

    metrics-listen-address: "0.0.0.0:{{ $.Values.metrics.port }}"
{{- end }}
