{{- range $itemKey, $itemValue := $.Values.chains }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $itemKey | lower }}-{{ include "consumer.fullname" $ }}
  labels:
    {{- include "consumer.labels" $ | nindent 4 }}
    app.lavanet.io/chain: {{ $itemKey | lower }}
spec:
  {{- if not $.Values.autoscaling.enabled }}
  replicas: {{ $.Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "consumer.selectorLabels" $ | nindent 6 }}
      app.lavanet.io/chain: {{ $itemKey | lower }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
      {{- with $.Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "consumer.selectorLabels" $ | nindent 8 }}
        app.lavanet.io/chain: {{ $itemKey | lower }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "consumer.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: import-keys
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command: ["sh", "-c"]
          args:
            - |
              if [ -f /lava/.key-{{ $.Values.wallet }}.imported ]; then
                echo "Key {{ $.Values.wallet }} has already been exported, exiting..."
                exit 0
              fi

              echo $KEY_PASSWORD | lavap keys \
              import {{ $.Values.wallet }} /tmp/keyfile/{{ $.Values.key.secretKey }} \
              --keyring-backend {{ $.Values.keyringBackend }}

              touch /lava/.key-{{ $.Values.wallet }}.imported
          env:
            - name: KEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.key.passwordSecretName }}
                  key: {{ $.Values.key.passwordSecretKey }}
          volumeMounts:
            - name: "private-key-volume"
              mountPath: /tmp/keyfile/{{ $.Values.key.secretKey }}
              subPath: {{ $.Values.key.secretKey }}
              readOnly: true
            - mountPath: "/lava"
              name: data
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          args:
            - rpcconsumer
            - config.yml
            - --from
            - {{ $.Values.wallet }}
            - --keyring-backend
            - {{ $.Values.keyringBackend }}
            - --chain-id
            - {{ $.Values.chainId }}
            - --node
            - {{ $.Values.node }}
            - --geolocation
            - {{ $.Values.geolocation | quote }}
            - --log_level
            - {{ $.Values.log.level }}
            - --log_format
            - {{ $.Values.log.format }}
            {{- if $.Values.cache.enabled }}
            - --cache-be
            - {{ $.Values.cache.address }}
            {{- end }}
            {{- if $.Values.disableConflictTransactions }}
            - --disable-conflict-transactions
            {{- end }}
            {{- if $.Values.relayServerAddress }}
            - --relay-server-address
            - {{ $.Values.relayServerAddress }}
            {{- end }}
            {{- if $.Values.reportsBeAddress }}
            - --reports-be-address
            - {{ $.Values.reportsBeAddress }}
            {{- end }}
            {{- range $i, $val := $.Values.additionalArgs }}
            - {{ $val | quote }}
            {{- end }}
          ports:
          {{- $interfaces := dict }}
          {{- range $interfaceDetails := $itemValue.interfaces }}
          {{- $_ := set $interfaces $interfaceDetails.interface . }}
          {{- end }}
          {{- range $interfaceEntry := $interfaces }}
            - name: {{ $interfaceEntry.interface | lower }}
              containerPort: {{ $interfaceEntry.port }}
              protocol: TCP
          {{- end }}
          {{- if $.Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ $.Values.metrics.port }}
              protocol: TCP
          {{- end }}
          volumeMounts:
            - mountPath: "/lava"
              name: data
            - mountPath: /lava/config/config.yml
              subPath: config.yml
              name: config
          {{- if $.Values.metrics.enabled }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: {{ $.Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $.Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ $.Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ $.Values.livenessProbe.successThreshold }}
            failureThreshold: {{ $.Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: {{ $.Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $.Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ $.Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ $.Values.readinessProbe.successThreshold }}
            failureThreshold: {{ $.Values.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      volumes:
        - name: "private-key-volume"
          secret:
            secretName: {{ $.Values.key.secretName }}
            optional: false
        - name: config
          configMap:
            name: {{ $itemKey | lower }}-{{ include "consumer.fullname" $ }}
            items:
              - key: config.yml
                path: config.yml
        - name: data
          {{- if $.Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ $itemKey | lower }}-{{ include "consumer.fullname" $ }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
