{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "consumer.fullname" . }}
  labels:
    {{- include "consumer.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
      {{- range $itemKey, $itemValue := $.Values.chains }}
      {{- $interfaces := dict }}
      {{- range $interfaceDetails := $itemValue.interfaces }}
      {{- $_ := set $interfaces $interfaceDetails.interface . }}
      {{- end }}
      {{- range $interfaceEntry := $interfaces }}
      {{- if (ne ($interfaceEntry.interface | lower) "grpc") }}
        - "{{ $itemKey | lower }}-{{ $interfaceEntry.interface | lower }}.{{ include "consumer.domain" $ }}"
      {{- end }}
      {{- end }}
      {{- end }}
      {{- with .Values.ingress.tlsSecretName }}
      secretName: {{ . }}
      {{- else }}
      secretName: consumer-tls
      {{- end }}
  {{- end }}
  rules:
    {{- range $itemKey, $itemValue := $.Values.chains }}
    {{- $interfaces := dict }}
    {{- range $interfaceDetails := $itemValue.interfaces }}
    {{- $_ := set $interfaces $interfaceDetails.interface . }}
    {{- end }}
    {{- range $interfaceEntry := $interfaces }}
    {{- if (ne ($interfaceEntry.interface | lower) "grpc") }}
    - host:
        {{- if $.Values.global.usePathBasedRouting | default false }}
        {{ include "consumer.domain" $ }}
        {{- else }}
        {{ $itemKey | lower }}-{{ $interfaceEntry.interface | lower }}.{{ include "consumer.domain" $ }}
        {{- end }}
      http:
        paths:
          - path:
              {{- if $.Values.global.usePathBasedRouting | default false }}
              /{{ $itemKey | lower }}-{{ $interfaceEntry.interface | lower }}
              {{- else }}
              {{ $.Values.ingress.path }}
              {{- end }}
            pathType: {{ $.Values.ingress.pathType }}
            backend:
              service:
                name: {{ $itemKey | lower }}-{{ include "consumer.fullname" $ }}
                port:
                  name: {{ $interfaceEntry.interface | lower }}
    {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
