{{- if $.Values.persistence.enabled }}
{{- range $itemKey, $itemValue := $.Values.chains }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  {{ $itemKey | lower }}-{{ include "consumer.fullname" $ }}
  labels:
    {{- include "consumer.labels" $ | nindent 4 }}
    app.lavanet.io/chain: {{ $itemKey | lower }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  {{- range $.Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ $.Values.persistence.size | quote }}
{{- end }}
{{- end }}
