{{- range $itemKey, $itemValue := $.Values.chains }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $itemKey | lower }}-{{ include "consumer.fullname" $ }}
  labels:
    {{- include "consumer.labels" $ | nindent 4 }}
    app.lavanet.io/chain: {{ $itemKey | lower }}
spec:
  type: {{ $.Values.service.type }}
  ports:
  {{- $interfaces := dict }}
  {{- range $interfaceDetails := $itemValue.interfaces }}
  {{- $_ := set $interfaces $interfaceDetails.interface . }}
  {{- end }}
  {{- range $interfaceEntry := $interfaces }}
    - port: {{ $interfaceEntry.port }}
      targetPort: {{ $interfaceEntry.interface | lower }}
      protocol: TCP
      name: {{ $interfaceEntry.interface | lower }}
  {{- end }}
  {{- if $.Values.metrics.enabled }}
    - name: metrics
      targetPort: metrics
      port: {{ $.Values.metrics.port }}
      protocol: TCP
  {{- end }}
  selector:
    {{- include "consumer.selectorLabels" $ | nindent 4 }}
    app.lavanet.io/chain: {{ $itemKey | lower }}
{{- end }}
